version: "3.5"

services:
  paper:
    image: kappa
    # image: ghcr.io/isaacsancheza/paper:42e3de79eca83201e32520b2370a4d77df8133ed
    ports:
      - "25565:25565"
    volumes:
      - "$PWD/paper:/paper"
    environment:
      - Xms=4G
      - Xmx=4G
