version: "3.5"

services:
  paper:
    image: ghcr.io/isaacsancheza/paper
    ports:
      - "25565:25565"
      - "25575:25575"
    volumes:
      - paper:/paper
      - $PWD/server.properties:/paper/server.properties
    environment:
      - Xms=4G
      - Xmx=4G

volumes:
  paper:
